public class Calculator2 {
        public static void welcomeMessage(){
        system.debug('welcome to apex calc');
    }
    public static void printNewMessage(string msg){
        system.debug(msg);
    }
    //return string, append '...ok cool' to parameter
    //public string printAndReturnMessage(string msg){
      //  string tempStr = msg + '...Ok cool.';
        //return tempStr;
    
    
}
